ydlidar_ros2_driver:
  ros__parameters:
    port: /dev/ttyUSB0
    frame_id: laser_frame
    ignore_array: ""
    baudrate: 115200
    lidar_type: 1
    device_type: 1
    sample_rate: 5
    abnormal_check_count: 2
    resolution_fixed: false
    reversion: false
    inverted: false
    auto_reconnect: true
    isSingleChannel: false
    intensity: false
    support_motor_dtr: true
    angle_max: 180.0
    angle_min: -180.0
    range_max: 16.0
    range_min: 0.12
    frequency: 10.0
    invalid_range_is_inf: false

